### ISSUE TITLE
TypeError: lightTxHashes.push is not a function

### ISSUE THREAD

**Issue by Jessieluu** [BOLT-Protocol/wizard_nodejs#31]
```JS 
 _appendReceiptHash = async (stageHeight, lightTxHash) => {
    let lightTxHashes;
    try {
      lightTxHashes = await this.db.get(stageHeight);
    } catch (e) {
      lightTxHashes = [];
    } finally {
      lightTxHashes.push(lightTxHash);
      await this.db.put(stageHeight, lightTxHashes);
    }
  }
```
Typeof data from level db.get is "string", so this function got the TypeError, because string type don't have push function, it need to be transfer to array type.

**Comment by sc0Vu** [comment]
Ben: Need to set `valueEncoding` to `json`

See: https://github.com/BOLT-Protocol/wizard_nodejs_demo/blob/master/testProposeDeposit.js#L7

```JS
let db = level('./db', { valueEncoding: 'json' });
```
